name: cs230Project
channels:
  - pytorch
  - defaults
dependencies:
  - bayesian-optimization==1.0.1
  - matplotlib=3.0.2
  - numpy=1.15.4
  - python=3.6
  - scikit-learn=0.20.2
  - pandas=0.24.0
  - pillow=5.4.1
  - cudatoolkit=9.0
  - pytorch=1.0.1
  - torchvision=0.2.1
  - plotly=3.6.1
  - pip:
    - keras==2.2.4
    - tensorflow==1.12.0
    - h5py==2.9.0
    - tqdm==4.30.0